name: SC4001_macos
channels:
    - conda-forge
    - defaults

dependencies:
    # --- Python + pip ---
    - python=3.10
    - pip

    # --- Core ML packages ---
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tensorboard
    - transformers
    - huggingface_hub
    - tqdm
    - tokenizers
    - datasets

    # --- PyTorch ---
    - pip:
          # PyTorch
          - torch==2.6.0

          # NLP packages
          - spacy==3.8.4
          - spacy-legacy==3.0.12
          - spacy-loggers==1.0.5

          # Utilities
          - pydantic==2.11.1
          - fsspec==2025.3.0
          - einops==0.8.1
          - rich==13.9.4

    # --- Cross-platform basics (retained) ---
    - absl-py
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - arrow-cpp
    - astunparse
    - async-timeout
    - attrs
    - aws-c-auth
    - aws-c-cal
    - aws-c-common
    - aws-c-compression
    - aws-c-event-stream
    - aws-c-http
    - aws-c-io
    - aws-c-mqtt
    - aws-c-s3
    - aws-c-sdkutils
    - aws-checksums
    - aws-crt-cpp
    - aws-sdk-cpp
    - blinker
    - bottleneck
    - brotli-python
    - bzip2
    - c-ares
    - ca-certificates
    - cachetools
    - certifi
    - cffi
    - charset-normalizer
    - click
    - colorama
    - cryptography
    - dill
    - filelock
    - flatbuffers
    - frozenlist
    - gast
    - gflags
    - giflib
    - glog
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpc-cpp
    - grpcio
    - h5py
    - hdf5
    - idna
    - importlib-metadata
    - joblib
    - jpeg
    - keras
    - keras-preprocessing
    - krb5
    - libarrow
    - libbrotlicommon
    - libbrotlidec
    - libbrotlienc
    - libcurl
    - libedit
    - libev
    - libevent
    - libffi
    - libgoogle-cloud
    - libgrpc
    - libnghttp2
    - libpng
    - libprotobuf
    - libsqlite
    - libssh2
    - libthrift
    - libutf8proc
    - libuuid
    - libzlib
    - lz4-c
    - markdown
    - markupsafe
    - multidict
    - multiprocess
    - ncurses
    - numexpr
    - parquet-cpp
    - protobuf
    - pyarrow
    - pyarrow-hotfix
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pyjwt
    - requests
    - requests-oauthlib
    - rsa
    - s2n
    - safetensors
    - setuptools
    - six
    - snappy
    - sqlite
    - tbb
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - termcolor
    - threadpoolctl
    - tk
    - typing-extensions
    - typing_extensions
    - tzdata
    - urllib3
    - werkzeug
    - wheel
    - wrapt
    - xxhash
    - xz
    - yaml
    - yarl
    - zipp
    - zlib
    - zstd
